# Análise Exploratória e Preparação de Dados

## Ataques e perdas registradas na Guerra Russo-Ucraniana

Este notebook apresenta uma análise exploratória de dados relacionados à Guerra Russo-Ucraniana, utilizando duas fontes em formatos distintos: CSV e JSON.

O objetivo é realizar a coleta, identificação, preparação e exploração dos dados, buscando compreender sua estrutura, características, distribuição temporal e principais padrões observáveis.

## 1. Importação e identificação dos dados

Nesta etapa são carregadas as bibliotecas necessárias e realizada uma primeira inspeção das duas bases utilizadas no projeto.

In [21]:
import pandas as pd
import json

### 1.1 Dataset de ataques

O primeiro conjunto de dados está armazenado em formato CSV e contém registros relacionados a ataques com mísseis e veículos aéreos não tripulados.

Inicialmente, será realizada apenas a leitura e inspeção dos registros, sem aplicação de tratamentos.

In [22]:
csv_path = "../data/raw/missile_attacks_daily.csv"

df_attacks = pd.read_csv(csv_path)

df_attacks.head()

,time_start,time_end,model,launch_place,target,target_main,status_data,launched,destroyed,not_reach_goal,...,num_fall_fragment_location,is_shahed,border_crossing,carrier,affected region,destroyed_types,destroyed_details,launched_details,launch_place_details,source
0,2026-10-23 18:00,2026-10-24 08:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,NaN,126.0,101.0,0.0,...,5.0,NaN,{},NaN,NaN,"{'Turbojet': {'launched': 61, 'destroyed': 50}}","{'south': 11, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid02krpG8X8gHJgZtJuSAXHXZhxAjz...
1,2026-10-23 18:00,2026-10-24 08:00,Geran-4 and Geran-5,NaN,west,Rivne oblast and Volyn oblast and Khmelnytskyi...,NaN,43.0,43.0,NaN,...,NaN,NaN,{},NaN,NaN,NaN,NaN,NaN,NaN,PvkZahid/posts/pfbid02jSUHVi4cHwnWgLjaj2AsjQhp...
2,2026-10-22 18:00,2026-10-23 08:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,NaN,176.0,140.0,0.0,...,13.0,NaN,{},NaN,NaN,"{'Turbojet': {'launched': 92, 'destroyed': 68}}","{'south': 37, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid035vtrJfou8Wu6D2AWsRSmsRamrw...
3,2026-10-22 18:00,2026-10-23 08:00,Geran-4 and Geran-5,NaN,west,Rivne oblast and Volyn oblast and Khmelnytskyi...,NaN,52.0,52.0,NaN,...,NaN,NaN,{},NaN,NaN,NaN,NaN,NaN,NaN,PvkZahid/posts/pfbid0euvwGUwU5mTczzYRF3KdcfUnA...
4,2026-10-23,2026-10-23,X-59/X-69,Crimea,south,NaN,NaN,1.0,0.0,NaN,...,NaN,NaN,{},NaN,NaN,NaN,NaN,NaN,NaN,PvKPivden/posts/pfbid04j17geDZg8oSiFodcFPucnfQ...

In [23]:
df_attacks.shape

(4285, 22)

In [24]:
df_attacks.columns.tolist()

['time_start',
 'time_end',
 'model',
 'launch_place',
 'target',
 'target_main',
 'status_data',
 'launched',
 'destroyed',
 'not_reach_goal',
 'still_attacking',
 'num_hit_location',
 'num_fall_fragment_location',
 'is_shahed',
 'border_crossing',
 'carrier',
 'affected region',
 'destroyed_types',
 'destroyed_details',
 'launched_details',
 'launch_place_details',
 'source']

In [25]:
df_attacks.head()

,time_start,time_end,model,launch_place,target,target_main,status_data,launched,destroyed,not_reach_goal,...,num_fall_fragment_location,is_shahed,border_crossing,carrier,affected region,destroyed_types,destroyed_details,launched_details,launch_place_details,source
0,2026-10-23 18:00,2026-10-24 08:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,NaN,126.0,101.0,0.0,...,5.0,NaN,{},NaN,NaN,"{'Turbojet': {'launched': 61, 'destroyed': 50}}","{'south': 11, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid02krpG8X8gHJgZtJuSAXHXZhxAjz...
1,2026-10-23 18:00,2026-10-24 08:00,Geran-4 and Geran-5,NaN,west,Rivne oblast and Volyn oblast and Khmelnytskyi...,NaN,43.0,43.0,NaN,...,NaN,NaN,{},NaN,NaN,NaN,NaN,NaN,NaN,PvkZahid/posts/pfbid02jSUHVi4cHwnWgLjaj2AsjQhp...
2,2026-10-22 18:00,2026-10-23 08:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,NaN,176.0,140.0,0.0,...,13.0,NaN,{},NaN,NaN,"{'Turbojet': {'launched': 92, 'destroyed': 68}}","{'south': 37, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid035vtrJfou8Wu6D2AWsRSmsRamrw...
3,2026-10-22 18:00,2026-10-23 08:00,Geran-4 and Geran-5,NaN,west,Rivne oblast and Volyn oblast and Khmelnytskyi...,NaN,52.0,52.0,NaN,...,NaN,NaN,{},NaN,NaN,NaN,NaN,NaN,NaN,PvkZahid/posts/pfbid0euvwGUwU5mTczzYRF3KdcfUnA...
4,2026-10-23,2026-10-23,X-59/X-69,Crimea,south,NaN,NaN,1.0,0.0,NaN,...,NaN,NaN,{},NaN,NaN,NaN,NaN,NaN,NaN,PvKPivden/posts/pfbid04j17geDZg8oSiFodcFPucnfQ...

### 1.2 Dataset de perdas

O segundo conjunto de dados está armazenado em formato JSON e apresenta registros diários relacionados a diferentes categorias de perdas, incluindo pessoal, veículos, equipamentos e outros recursos.

In [26]:
json_path = "../data/raw/equipments and personal losses_daily.json"

with open(json_path, "r", encoding="utf-8") as file:
    losses_json = json.load(file)

In [27]:
losses_json.keys()

dict_keys(['legend', 'data'])

In [28]:
len(losses_json["data"])

1705

In [29]:
losses_json["legend"]

{'tanks': 'Tanks',
 'apv': 'Armoured Personnel Vehicle',
 'artillery': 'Artillery systems',
 'mlrs': 'MLRS',
 'aaws': 'Anti-Aircraft Warfare Systems',
 'aircraft': 'Aircraft',
 'helicopters': 'Helicopters',
 'uav': 'UAV',
 'ugv': 'Unmanned Ground Vehicle',
 'vehicles': 'Vehicles',
 'boats': 'Boats',
 'submarines': 'Submarines',
 'se': 'Special Equipment',
 'missiles': 'Cruise Missiles',
 'personnel': 'Personnel'}

In [30]:
list(losses_json["data"].items())[:3]

[('2022.02.24',
  {'tanks': 30,
   'apv': 130,
   'artillery': 0,
   'mlrs': 0,
   'aaws': 0,
   'aircraft': 7,
   'helicopters': 6,
   'uav': 0,
   'ugv': 0,
   'vehicles': 0,
   'boats': 0,
   'submarines': 0,
   'se': 0,
   'missiles': 0,
   'personnel': 800}),
 ('2022.02.25',
  {'tanks': 70,
   'apv': 410,
   'artillery': 0,
   'mlrs': 0,
   'aaws': 0,
   'aircraft': 9,
   'helicopters': 12,
   'uav': 0,
   'ugv': 0,
   'vehicles': 0,
   'boats': 0,
   'submarines': 0,
   'se': 0,
   'missiles': 0,
   'personnel': 2200}),
 ('2022.02.26',
  {'tanks': 50,
   'apv': 166,
   'artillery': 50,
   'mlrs': 4,
   'aaws': 1,
   'aircraft': 11,
   'helicopters': 8,
   'uav': 2,
   'ugv': 0,
   'vehicles': 0,
   'boats': 2,
   'submarines': 0,
   'se': 0,
   'missiles': 0,
   'personnel': 1500})]